language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=2.132
  matrix:
    - TAG=2.132 JENKINS_VER=2.132 EXTRA_TAG=2

script:
  - make

after_success:
  - . "${TRAVIS_BUILD_DIR}/release"
