language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=2.121.2
  matrix:
    - TAG=2.121.2 JENKINS_VER=2.121.2 EXTRA_TAG=2

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release"
