language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=2.112
  matrix:
    - TAG=2.112 JENKINS_VER=2.112 EXTRA_TAG=2

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/travis_release"
