language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=2.114
  matrix:
    - TAG=2.114 JENKINS_VER=2.114 EXTRA_TAG=2

script:
  - make && make test

after_success:
  - . "${TRAVIS_BUILD_DIR}/release"
